### ISSUE TITLE
CLR: ephys fragments need to be able to handle multiple sets of protocol conditions

### ISSUE THREAD

**Issue by ChristopherRees** [Hippocampome-Org/php#215]
When a single ephys original ID has multiple interpretations, the protocol does not change.

See Granule cells / Vrest / Staley article.  There are 2 interpretations, both from Table 1 (ref IDs in the database are 10700 and 10709).  Both are linked to fragment id 8316 (Staley's Table 1), which is stored as having a single pg location and set of protocols.  However, ref ID 10700 should show that the method is microelectrodes; ref ID 10709 is patch clamp.  Therefore, these protocols/conditions should not be tied to the fragment (or we need to create a second, duplicate fragment during DB import).

We should see:
Ref id 10700: -74.0 ± 2.1 mV (n=11) is rats | microelectodes | 34deg (body)
Ref id 10709: -84.0 ± 1 mV (n=31) is rats | patch clamp | 34deg (body)

but the set of conditions that include patch clamping is not stored anywhere in the DB

Same issue occurs in CA1 Pyr / Vrest / Routh article (3 interpretations for this fragment).  Possibly elsewhere.

See CLR for clarification if needed.

**Comment by dhamilt5** [comment]
From: Christopher Rees
Sent: Wednesday, December 23, 2015 12:43 AM
To: David Hamilton
Cc: Amar Gawade; sdesai20; Diek W Wheeler
Subject: Re: Issue 215 ‐ Ephys fragments need to be able to handle multiple sets of protocol conditions
Hi David,
If I might, let me elaborate on the problem and make sure we all understand it and the ramifications of different potential solutions.
If you look in the database, in the fragment table, and pull up records with the original_id=100001771720100 (i.e. SELECT * FROM [insert_your_DB_name].Fragment where original_id=100001771720100;), there are 2 results. There are 2 records in the database with the same original_id. They actually have different unique IDs (8152 and 8389), so I think it should be possible to detect this in our DB querying and, if we have multiple original_ids returned, list each one separately on the evidence
page, rather than the same one twice (which is what we do now: see Granule cells, Vrest, open the Staley evidence). ...
However, if we want to fix this on the original_id level, we’ll need to either modify the original_id construction (e.g. add more digits; I don’t recommend this) or else get tricky. As a reminder, the 15‐digit original_ids for ephys are constructed as follows:
1. Cell ID (4 digits)
2. Parameter ID (2 digits)
3. Last 4 digits of PMID (4 digits)
4. Figure/Table/Quote ID (5 digits: first digit=1 for figure, 2 for table, etc.; digits 2‐3 are for the fig number; digits 4‐5 are
to represent panel a, b, c, etc.)
In this case, we have 2 identical original IDs because we’re talking about the same cell type, same parameter, and the same table in the same PMID. I think the non‐PHP‐coding solution here is to pretend that the different columns in this table are actually different panels of the table (Table 1A, 1B, and 1C). Therefore, the data in the first two columns would actually lead to two unique original_ids: 100001771720101 (Table 1A) and 100001771720102 (Table 1B). If you think that this is the way to fix things, I will need to have Alexander manually make the change in his spreadsheet and call it “Table 1A” and “Table 1B” instead of just “Table 1”. But before I do this, I would like for someone to query the database and get me a list of ALL cases where we have identical original IDs. I’d rather just Alexander make all these changes at once.
Please let me know if any of this isn’t clear, and I’ll try to re‐explain.
Thanks very much! Christopher

**Comment by dhamilt5** [comment]
201512292254
I have done the required changes for the issue 215 and property_page_ephys.php was the only file modified. My modifications are present at line 1626-1635. Please check and let me know if any modifications has to be done.
Thanks and regards,
Smitha

diff ../php_clone_201512280205/property_page_ephys.php property_page_ephys.php
1601c1601
< 					// retriveve information about fragment: --------------
---
> 					// retrieve information about fragment: --------------
1625a1626,1636
> 					// To print articles according to unique original ID
> 					$found=0;
> 					$original_id_list[$i1] = $original_id;
> 					for($i2=0; $i2<$i1; $i2++)
> 					{
> 						if($original_id == $original_id_list[$i2])
> 							$found=1;
> 					}
> 					if($found == 1)
> 						break;
> 		
1628c1639
< 					$id_article = $articleevidencerel -> getarticle_id_array(0);;
---
> 					$id_article = $articleevidencerel -> getarticle_id_array(0);

**Comment by drdiek** [comment]
201601051111
I think a php only solution does not completely solve our problems. Although querying for the original IDs seems to fix the problem for the citation side of things, it does not allow for the distinguishing of the separate figures that are needed. I think Christopher's solution for treating separate columns as panels is a good solution to this. Thoughts?
Diek

**Comment by drdiek** [comment]
201601281759
"Same issue occurs in CA1 Pyr / Vrest / Routh article (3 interpretations for this fragment)." The 3 separate interpretations are now appearing, except all three protocols say "rats," whereas 2 of the interpretations refer to mice. Also, the highlighted tables are not appearing, even though the files are present in the attachment_ephys folder.
Diek
