### ISSUE TITLE
CLR: marker names that include a forward slash have empty columns in the extended matrix

### ISSUE THREAD

**Issue by ChristopherRees** [Hippocampome-Org/php#259]
Examples: AMPAR2/3, GluR2/3, mGluR2/3

The forward slash will need to be replaced by another character.  We already do similar remappings in the PHP code for other problematic names, so take a look at how we solved that.

**Comment by dhamilt5** [comment]
Actually, any column in the matrix that is totally blank (i.e. no flags and/or grey squares) is not correct.

**Comment by dhamilt5** [comment]
From: Christopher Rees
Sent: Thu 1/28/2016 11:45 PM
It looks like Padmini did a nice job of getting the missing data into the empty columns in the marker matrix.  Everything looks good there, and I’m reasonably certain that all of the missing triangle icons are now showing up.  However, the changes need to be carried through in 3 other places.  Specifically, the marker name variables getting passed in the hyperlinks are also not working correctly. In some cases, we’re generating incorrect links in the marker matrix that point to "neuron by marker” pages.  (For example, click on the GABAaalpha2 column heading in the matrix.  It will lead to an empty neuron by marker page.) In some cases, we’re generating incorrect links in the marker matrix that point to marker evidence pages.  (For example, click on the orange triangle in the Granule cell row and GABAadelta column.  It will lead to an empty evidence page.) Similarly, in some cases, we’re generating the same incorrect links on the neuron pages that point to marker evidence pages.  (For example, on the Granule cell neuron page, click on GABAadelta in the mixed expression table.  It will lead to an empty evidence page.) Again, the problem is that the link address itself has the wrong marker name embedded in it.  These need to be remapped as well.  Once they are, the empty pages will populate correctly.
