### ISSUE TITLE
K1M:[Search Engine]: decimal numbers are not correctly interpreted

### ISSUE THREAD

**Issue by k1moradi** [Hippocampome-Org/php#367]
The following two search queries produce different results:

Connection:(Presynaptic:(Neurotransmitter:Excitatory AND Morphology:(Axons:CA1:???1 OR Soma:CA1:???1)), Postsynaptic:(Morphology:(Dendrites:CA1:0001 AND Soma:CA1:???1) AND Electrophysiology:sag_ratio:<=0.7))

Connection:(Presynaptic:(Neurotransmitter:Excitatory AND Morphology:(Axons:CA1:???1 OR Soma:CA1:???1)), Postsynaptic:(Morphology:(Dendrites:CA1:0001 AND Soma:CA1:???1) AND Electrophysiology:sag_ratio:<=0.7**0**))

**Comment by drdiek** [comment]
I think I know how to fix this problem. If I slightly modify line 82 in SearchEngine/Page.php to read 

                    $roundDigit=strlen($propertyValue)-(strpos($propertyValue,".")+1)+1;

then the rounding problem seems to go away. HOWEVER, I seem to be getting different search results between my local instantiation of the portal and csv2db. For csv2db, I get 30 hits, and for my local portal I get 4 hits. I do not understand why I should be getting so many fewer results locally. I think I believe the results coming from csv2db more than I trust my local results, in part because of the inclusion of CA1 Horizontal Axo-axonic cells in the postsynaptic listing in my local results.

**Comment by Anjan1519** [comment]
Nikhil has encountered the same issue of getting 5 records on the local machine which is surely wrong. But I and David have got 30 records which are same as our csvdb server. Nikhil has sorted this issue by re-instantiating the database. This is the easiest solution we could find. But we are still looking into the issue the find out the actual reason
