### ISSUE TITLE
GAA: counter issue

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#378]
The main page says Hits: 91, Unique Visits: 12, which surely must be wrong. Hopefully we can retrieve and reinstate the historical records and fix the glitch...? - GAA

I just now restored the "hits.txt" file back to my most recent backup from Dec 9, 2017. To my knowledge, there is no regular backup of this server, so we may not be able to recover the snapshot of "hits.txt" prior to this reset.
Going forward, we can take regular (e.g. monthly) snapshots of this file just in case this happens again. Another thing that we should check is if there is a max on the counter we are using that then causes the reset. If that is the case, and if we can figure out what that max is, we can then estimate what the count was at the time of the reset. This counter code was lifted from open source back in 2012 or thereabouts and may only be a 32 bit counter. We will likely want to revisit this counter code and upgrade it. - DJH

**Comment by nmsutton** [comment]
I have now installed new php software for running the counter. The appearance on the site looks the same but it is running on different code. It now uses a database for tracking hits and no longer a text file that can get overwritten with updates to the code. 

The new php code has not yet been added to the github repo because I will need to do a doc diff between the site's server files and the github files hosted here to make sure nothing is lost by uploading them here. I know this repo is behind the site's files because the site is on v1.5 while this repo is on v1.3. Better connecting this github repo to the server hosted files is also an issue for a later time. 

For now, I am leaving this issue open until I also upload the updated files to github. Generally speaking, this issue appears fixed because I have checked it and the new code is continuing to work on the server site. Automated database backups would also both benefit the site and the new code added as well. From what I understand that is in the pipeline for the future but also counts as an issue to work on. Once I get a chance to upload the new code to github I will close this issue.

**Comment by Nikhilkoneru** [comment]
I will create a cronjob in server to do a backup every month.

**Comment by nmsutton** [comment]
That sounds great! Thanks, Nikhil. Let us know if any assistance is needed for that. One thing is if possible when doing that please write code to periodically remove old backups also. We probably don't need monthly backups indefinitely, so if any backups are greater than a year old they can be automatically discarded. That may be a bit more advanced so just getting the backups working in the first place would be great! Also, please include backups for the databases for the 4 main versions of the site and the new counters database I created. We appreciate your help with this. I will try to create a new ticket for this work so that it will be documented.
