### ISSUE TITLE
GAA: [connectivity] Refuted connections not being listed properly on Neuron Pages

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#379]
In the connectivity matrix, there are certain connections between cell types that are marked with a large red X, which indicates that the two cell types are not connected to each other. These refuted connections should also appear listed on the Neuron Page. In the example highlighted below in the connectivity matrix, CA3 Axo-axonic neurons do not make contact with 11 other neuron types. These 11 types are being listed on the Neuron Page as being connected, whereas they should be in the column for "Potential targets known to be avoided."
![slide1](https://user-images.githubusercontent.com/4380011/51131013-7b56e300-17fc-11e9-9646-4f62b634df77.JPG)
![slide2](https://user-images.githubusercontent.com/4380011/51131014-7b56e300-17fc-11e9-98e5-74404a078d81.JPG)

**Comment by Nikhilkoneru** [comment]
After analyzing the code for "targets of output" I came to know that it is problem with database entries
in TypeTypeRel table. The code is written in a way that it will calculate array difference between possible connections and potential targets know to be avoided. Since for few neuron types we didn't define negative entries in TypeTypeRel table we are seeing them as potential targets.

For example for CA3 Axo-Axonic:
SELECT * FROM TypeTypeRel WHERE Type1_id = '2028'  using this query you can see only positive connections. We didn't add any negative entries with other neurons.If we can add negative entries  with other neurons which are marked (red x) in TypeTypeRel table everything will work as we want.

Note: Connectivity matrix is loaded from json not from database so it is working perfectly even if we didn't have correct entries in Database

**Comment by drdiek** [comment]
There is an updated spreadsheet conndata.xlsx, which is based off of Keivan's latest information, which defines the positive and negative connections. A 5, 4, or 1 in the Connection? column indicates a positive connection. A 0 or -1 in the Connection? column indicates a negative connection.
[conndata.xlsx](https://github.com/Hippocampome-Org/php/files/3672967/conndata.xlsx)

**Comment by drdiek** [comment]
Use of the updated conndata.xlsx from Keivan fixed the problem.
