### ISSUE TITLE
K1M: [ephys]: Missing table figure on ephys page

### ISSUE THREAD

**Issue by k1moradi** [Hippocampome-Org/php#399]
On the evidence page of CA1 Pyramidal Rin related to PMID=19675296 the table 1 figure is missing. The labeling is confusing also. We have two mice numbers one of them for C57BL/6 and the other for 129/SvEv. "<% 4000%>" should be converted to a link or something else and become invisible. The metadata is missing as well (i.e. solutions, slicing and ...)
![image](https://user-images.githubusercontent.com/18602635/56148609-ad512000-5f78-11e9-8e97-773b875951c2.png)

**Comment by drdiek** [comment]
I am not sure that the protocol_tag column in the Attachment database table is being read and interpreted properly in order to display the correct figures here. Since all 3 entries refer to the same figure and the same ephys parameter, their original_ids are identical, and they need to be distinguished from each other by their protocol_tags.

**Comment by k1moradi** [comment]
Should we ask Alexander?

**Comment by drdiek** [comment]
No, Alexander is not needed to rectify this problem. His spreadsheets are fine. The problem lies in the php code that is interpreting the entries in the database. The protocol_tags are an extra measure that is not normally needed to access 98% of the ephys information.
