### ISSUE TITLE
CT: [neurites] Display parcel breakdown of values on Evidence pages for synapse probabilities

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#459]
![syn_prob](https://user-images.githubusercontent.com/4380011/70456684-9b2e6f80-1a7c-11ea-8849-4cfbcab9c873.jpg)

**Comment by nmsutton** [comment]
@drdiek I have attempted to complete this task. Please review the work and if it looks completed please close this issue.

**Comment by drdiek** [comment]
@nmsutton It is getting there. Despite what was depicted in the mock up, I now think we should not be displaying all 3 breakdowns at the same time, but display them individually according to the type of information being evidenced: i.e. potential number of synapses, number of contacts, or probability of connection. Also, despite what is in the mockup, I think the font used should be smaller and more in line with the font sizes used for the rest of the page.

**Comment by nmsutton** [comment]
@drdiek Thanks for reviewing this. I have updated the content as you requested. I also changed the number of significant digits from 3 to 5 (as opposed to the mockup display) because that is more in-line with the main matrix values and I found with "Synaptic Probabilities" some values will just show up as 0.00 instead of 0.0012 in some cases if that is not done.
