### ISSUE TITLE
GAA: [neurites] Clicking on values in a n-by-k or n-by-n synapse probabilities matrix should open a new tab

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#480]
This functionality should apply to the following matrices: Dendritic and Axonal Lengths, Somatic Distances of Dendrites and Axons, Number of Potential Synapses, Number of Contacts, and Synaptic Probabilities.

**Comment by nmsutton** [comment]
@drdiek I have fixed this issue. I found there appears to have been a bug in the hco function OpenInNewTab(aEle) where the code was set to ‘_self’ instead of ‘_blank’. I found this in markers_search.php, morphology_search.php, morphology.php, Izhikevich_model.php, as well as my new synpro code (I had copied from one of those) and I corrected it in all of them. It can be observed currently on the hco site by for example clicking a parcel name in the first row of the morphology matrix and it doesn’t open in a new tab. With the updated code on phpdev it now works on the synpro pages as well as those other related pages. 

I would assume it was an accident that the code was modified on those pages, so changing it won’t cause issues. This is as opposed to some intentional reason that is not known of. I seem to recall that Giorgio said it was wanted to be standard on the site that such links open in new tabs, and given the links are in a function OpenInNewTab, it seems that is the intended result. I have done limited testing of the new functionality on such pages but if you could please test this on both the synpro pages and others listed I would appreciate it. If this looks completed (including the other pages) please close this issue. Also, please tell me if you don’t want the code corrected in those original 4 pages and I will revert it back.

**Comment by drdiek** [comment]
@nmsutton it all looks good. Thank you for tracking this down. Everything appears to be working as expected.
