### ISSUE TITLE
CT: [neurites] Revamp the somatic distances Evidence pages

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#481]
1) Change the title from "Synapse probabilities evidence page" to "Synapse Probabilities - Somatic Distances of Dendrites/Axons Evidence page"
2) Modify the "axon_dendrite_somata" phrase in the Neuron Type section to be either "axon" or "dendrite" as appropriate
3) Remove one of the axon and dendrite check boxes as appropriate, but do not list them both
4) After the Page location listing, add a "Somatic distances of dendrites" or "Somatic distances of axons" as appropriate, where the value listed should be a mean ± standard deviation (n = ?; min = ?; max = ?) for the given bibliographic entry.
5) Add "SWC somatic-distance paths" for the appropriate neurite
6) Add a clickable icon that leads to the appropriate RAR file
7) Instead of displaying the separate pictures for axons and dendrites for each parcel, display only the original whole image

![Somatic Distances Evidence pages](https://user-images.githubusercontent.com/4380011/75187505-23d1b900-5718-11ea-8bb7-e60be0c78d6b.jpg)

**Comment by drdiek** [comment]
@nmsutton please hold off on this Issue while I accommodate Giorigo's latest feedback on the display layout.

**Comment by drdiek** [comment]
@nmsutton this Issue is now ready to be addressed.

**Comment by nmsutton** [comment]
@drdiek I have completed this task. Please review it and if it looks acceptable please close this issue.

**Comment by drdiek** [comment]
@nmsutton it appears that the somatic distance measurement for a given figure has just a single value. Therefore, I believe we should just list the value and remove the parts that refer to the mean, standard deviation, n, min, and max.

**Comment by nmsutton** [comment]
@drdiek my apologies because there was a sql query bug in my code that caused it to appears as only 1 value but there are actually multiple values in some entries. I have corrected this. Multiple value [example 1](http://www.hippocampome.org/phpdev/property_page_synpro.php?id_neuron=1000&val_property=DG_H&color=red&page=1&sp_page=sd). I have also added that when only 1 value is detected the std, min, max are not reported and that number of values = 1 is included. Single value [example 2](http://www.hippocampome.org/phpdev/property_page_synpro.php?id_neuron=1041&val_property=DG_H&color=red&page=1&sp_page=sd). Please tell me if describing number of values = 1 is wanted to distinguish the entry from the ones that report on multiple values. 

I assume somatic distance is listed in micrometers, the same unit as the axon-dendrite lengths, and therefore I have added the unit for that. Please tell me if a different unit should be added after the value.

**Comment by drdiek** [comment]
@nmsutton I think we are very, very close. For example 1, could you please remove the decimal places from the "n =" portion of the parentheses, since this is just an integer value? For example 2, could you please replace "number of values = 1" with "(n = 1)?"

**Comment by nmsutton** [comment]
@drdiek sounds good, I have now applied the updates.
