### ISSUE TITLE
GAA: [neurites] Craft the Evidence page for the Number of Potential Synapses

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#490]
1) Change the title of the page to "Number of Potential Synapses Evidence Page"
2) Format the Connection Details section to include a From neuron type, a To neuron type, the type of connection being described, and the parcel that the Axons and Dendrites are located in
3) Include the new explanatory comment: "The average number of synapses per neuron pair is calculated by combining neuron type specific lengths of the presynaptic axons and the postsynaptic dendrites (evidenced below), the volume of the anatomical parcel in which they overlap, and estimates of the mean inter-bouton and inter-spine (or inter-shaft contact) distances as well as of the axon-dendrite interaction distance."
4) List all of the axonal evidence with accompanying figure depicting the full neuron
5) List the Axonal length in the appropriate parcel
6) List the Figure segmentation evidence
7) Link the PNG download icon to the appropriate figure file
8) List all of the dendritic evidence with accompanying figure depicting the full neuron
9) List the Dendritic length in the appropriate parcel
10) List the Figure segmentation evidence
11) Link the PNG download icon to the appropriate figure file

![Number of Potential Synapses](https://user-images.githubusercontent.com/4380011/75188809-dacf3400-571a-11ea-8474-ba546f45ab43.jpg)

**Comment by nmsutton** [comment]
@drdiek for all the N by N evidence pages arn't I including rar files instead of as described here "PNG download icon to the appropriate figure file"? I thought that is what we talk about when we last talked in person.

**Comment by drdiek** [comment]
@nmsutton Sorry, that was confusion on my part. I have just received confirmation from Carolina that the RAR files are only for the somatic distances. All of the other Evidence pages have PNG files associated with them, and the Number of Contacts page also has convex Hull estimation values.

**Comment by nmsutton** [comment]
@drdiek  Thanks! Regarding "type of connection being described". On the existing HCO connectivity page, the matrix provides a variable with connection_type as listed in its legend on the right. Since we are not using connectivity page evidence, should we not include that "type of connection"? If you know of another way to find that please share but I don't know where to find that variable value unless we were integrating connectivity page evidence.

**Comment by nmsutton** [comment]
@drdiek actually I think nevermind about the last comment. I found in the parcel breakdown page this type was found with "SELECT distinct target_E_or_I FROM number_of_contacts WHERE source_ID=$source_id and target_ID=$target_id;" so I should be able to get the type from that.

**Comment by nmsutton** [comment]
@drdiek I think this task may be completed now. Please look over the work and if it looks acceptable please close this issue.

**Comment by nmsutton** [comment]
@drdiek one other thing to mention is that in the type of connection info mentioned earlier the connectivity page includes a "$known_unknown_flag" variable. Since the NbyK evidence page does not have a known/unknown distinction currently, and that may need integrating connectivity page data, I assume it is fine for the type to only describe inhibitory/excitatory and not "known status" unless you say otherwise. 

For finding inhibitory/excitatory I am using target_E_or_I in the above stated query. There is also a source_E_or_I in the db columns. It makes sense to use target_E_or_I, and not source_E_or_I because that represents the type of connection between N1 and N2 right?

**Comment by drdiek** [comment]
@nmsutton No, it is the source_E_or_I that determines the connection type.

**Comment by nmsutton** [comment]
@drdiek thanks, I have now updated all relevant NbyN pages to use source_E_or_I.
