### ISSUE TITLE
GAA: [Evidence pages] Evidence page entries missing or incorrect

### ISSUE THREAD

**Issue by nmsutton** [Hippocampome-Org/php#493]
When browsing the morphology page incorrect evidence page entries are returned. Also, some evidence entries are missing in the synaptic probabilities evidence pages.

**Comment by nmsutton** [comment]
@drdiek An update to this work is that I have now recoded the NbyK and NbyM database data to be in separate tables from hco’s original tables. I have therefore also taken the limiting code off of the synpatic probabilities property pages so they should be returning all results available now. The morphology and other site section evidence pages appear to now be returning correct results in comparison with the main site (as opposed to previously returning incorrect ones in hippodevome). 

There are still some complex entries that have caused challenges in the past, for instance, book isbn codes that are intended to fit into number data type columns even though they have dashes in them. I have located existing hco php code that has removed such value data in the past and I will apply it to try to get all entries able to import into evidence. At that point perhaps there will be no missing evidence entries because those ones are included as well.

**Comment by drdiek** [comment]
@nmsutton this Issue is essentially a reiteration of Issue #485, which I apparently neglected to assign to you and which I have now closed as being redundant.

**Comment by drdiek** [comment]
@nmsutton it would be easy enough to remove the hyphens in the spreadsheets; however, if you feel that this is best addressed in the php code, please proceed.

**Comment by nmsutton** [comment]
@drdiek thanks, I read #485 previously but thought that refereed to an issue where the synpro evidence pages redirected to morphology evidence page when clicking on expanding evidence. That was an issue in the past but has been corrected for a while now it seems. I don’t know if it came back but it does not look like it does. Thanks for straitening out the Github issues regarding this.

For this, with the book isbn numbers an issue is that the same isbn number can have multiple article entries in the Article table because each has different titles. This creates a challenge where an isbn number does not uniquely identify an article entry. In the previously existing hco code for autogenerating ArticleEvidenceRel table it appears it just takes the first matching Article row with whatever isbn is given. For example:
row_object = Article.objects.filter(pmid_isbn=pmid_isbn).order_by('id').first() in csv2db’s morphdata_string_field.py (which I now use synpro_string_field.py to avoid interfering with prior code)
This will create a problem with the synaptic probabilities data because for isbn_ids unless the pmid_isbn and title are uniquely matched it will retrieve the wrong Article row. It appears I will need to write new php code to handle this for isbn_ids.

**Comment by drdiek** [comment]
@nmsutton for book ISBN numbers, use the first_page column in the Article table to distinguish between the different articles within a given book. That is what David created that column for.

**Comment by nmsutton** [comment]
@drdiek an update on this is that at least for testing purposes I have uploaded to phpdev the starting page 133 of isbn 9780195100273 revised versions of the Article and Fragment tables based on article, marker_fragment, and morph_fragment csv files I emailed you about. Any unexpected side effects of the changes can be tested for currently through phpdev, although hopefully there aren’t any.

**Comment by drdiek** [comment]
@nmsutton for record purposes, I am pasting in the email:

"I tested altering the starting page to 133 and unfortunately that appears to cause the book chapter to disappear from the results in the screenshot you sent me. Here is the link for reference (without it missing) in testing:
http://www.hippocampome.org/php/property_page_morphology.php?id_neuron=1000&val_property=DG_SMo&color=blue&page=1
The results go from 19 to 18 and the only missing entry it appears is Chapter 5: Structural and functional properties of hippocampal neurons Spruston N, McBain C. 

Based on the experience I have had with csv2db, the fragment csv data creates evidence then article connections by using pmid_isbn+starting_page to automate writing the article reference to the ArticleEvidenceRel. ArticleEvidenceRel is what provides the article info in the properties page based on the evidence_id detected. A challenge is that multiple csv files are used to create the Fragment table (I count 5 csv files with "fragment" in them in the original files) so I didn't know which csv file exactly the entry may be in. I ran a grep search to look for it and suspected I found the culprits. In marker_fragment.csv and morph_fragment.csv pmid_isbn_page is listed as 131 in multiple rows (39 of them in morph_fragment.csv and about 10 in marker_fragment.csv). I went into the files and corrected it, and attached is the updated article.csv, marker_fragment.csv, morph_fragment files. The article.csv file also has additional articles I added for synpro.

I am glad to say that after running csv2db with the updated files the book chapter then successfully shows up in the results in the example link above with the correct starting page number listed. If you run it, make sure csv2db is correctly copying files from iconv->utf8->dat because I have had multiple issues with that. I also tested if the missing chapter now appears in the NbyK matrix and I am glad to say it does (example, if the update is applied another evidence entry will appear in the example). Therefore, if the updates are made than it seems all data is hopefully loading correctly in the NbyK matrix at that point.

A concern is I don't know of what other ripple effects updating the values could have but hopefully there are none. As we talked about it is valuable to get the values correct so perhaps it is worth doing it. I refer to you for the decision about if the updates are wanted (around 50 value changes to fix it). Do you think the updates should be applied (it is understandable if you want to investigate it first before choosing)?"
