### ISSUE TITLE
CT: [neurites] In the column headers of the NxN matrices, increase the vertical spacing so that the entire neuron-type names can be seen

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#498]

**Comment by nmsutton** [comment]
@drdiek At last, I have found a solution to this. It is complex, involving 10 or more formatting changes, and required notable manual labor, because I needed to adjust by hand the positions of all 122 neuron names in the headers. The versions of the NbyN matrices are up now with the increased header sizes. Please check to confirm the NbyN matrices.

**Comment by drdiek** [comment]
@nmsutton I can't believe there isn't a better way than hand positioning everything. It looks as though 5 or 6 names are getting cut off at the top because of the width of the subregion labels. Can you please readjust so this is taken into account?

**Comment by nmsutton** [comment]
@drdiek yes, I will adjust that. You could be right that there is some better way but I was pushing for at least a beta release of the pages that I will explain in an email shortly so since the way I did it currently at least works it can be used unless an easier way is found. Based on a forum I ready in the past JQGrid isn't even supposed to be able to do the vertical orientation like it is shown on the site but HCO developers created some custom method to override the formatting. It is surprisingly more complex than it would seem it would be in my opinion. I appreciate your point though that there probably is some easier way but I don't know of it currently.

**Comment by drdiek** [comment]
@nmsutton Did they hand adjust all of the column headers in the original connectivity matrix?

**Comment by drdiek** [comment]
@nmsutton It turns out I am really struggling with this task. I have figured out how to increase the size of the column headers and re-adjust the starting positions of all of the names. I have also, with your assistance, determined how to increase the size of the From-To header. What I have not been able to figure out is how to shift down all of the neuron-type names, which are listed along the left, to compensate for the increased height of the From-To header.

**Comment by nmsutton** [comment]
@drdiek I will help take a look at this, can you please u/l your code to github and I will clone it and work from where you are at?

**Comment by drdiek** [comment]
@nmsutton OK, I have uploaded my changes to GitHub now. As you can see, the portion of the leftmost column, where it displays 'DG(18)' and 'Granule' needs to be shifted downward by 20px, but I have just been unable to figure out in which file the information is stored.

**Comment by nmsutton** [comment]
@drdiek Thanks. For your and my help on this in the future, I have uploaded the notes I took about this to the dev docs [site here](https://hco-dev-docs.readthedocs.io/en/latest/synaptic_probabilities/header_height.html). I will be using that to try to update this and if you want to in the future you can also.

**Comment by nmsutton** [comment]
@drdiek Using the [dev docs notes](https://hco-dev-docs.readthedocs.io/en/latest/synaptic_probabilities/header_height.html) I got a little further here. I got the matrix size larger with the larger header size you made but the individual neuron class names have not yet been realigned with the changes.

**Comment by drdiek** [comment]
@nmsutton It looks good.

**Comment by drdiek** [comment]
@nmsutton I will take care of adjusting the individual class names, while you dedicate yourself to more sophisticated problems.

**Comment by nmsutton** [comment]
@drdiek thanks for the help with this! I had been thinking previously that possibly there is a css property `text-align: left` ([link1](http://www.littlewebhut.com/css/text_align/), [link2](https://css-tricks.com/almanac/properties/t/text-align/)) or `float: left` ([link](https://css-tricks.com/almanac/properties/f/float/)) that could help auto-align them but I think they may still need offset due to the borders around them `position:relative;left:30` (note: `position:relative` is often required when adding `left`) ([link1](https://www.geeksforgeeks.org/css-left-property/), [link2](https://tailwindcss.com/docs/top-right-bottom-left/), [link3](http://www.littlewebhut.com/css/left/)). Maybe there is other alignment code also.

If such things don't work manually adjusting the positioning of them can work perhaps (as they are now manually positioned). Another challenge is that each browser and OS can interpret `px` size differently leading to different displays on each. I think auto-audjusting as described above can help reduce that issue. If I remember right using `em` instread of `px` may also reduce that issue between browsers. I know chrome is the official browser for the site so if it at least works on that it should be good to go.

**Comment by nmsutton** [comment]
Also, in addition to the comments I made a minute ago, adding `float: left !important` with `!important` can help override any other css formatting getting in the way.

**Comment by nmsutton** [comment]
@drdiek in addition to the two comments I just recently added here, attached to this post are special editions of the "Number of Potential Synapses" matrix page and connected json file that have limited rows and should make reloading for testing neuron class name header formatting adjustments close to instant rather than several seconds to reload each time. Github only allowed uploading them with .txt extensions but rename synapse_probabilities_ps_limit to have a .php extension and ps_db_results to have a .json extension.
[synapse_probabilities_ps_limit.txt](https://github.com/Hippocampome-Org/php/files/4428267/synapse_probabilities_ps_limit.txt)
[ps_db_results.txt](https://github.com/Hippocampome-Org/php/files/4428277/ps_db_results.txt)

**Comment by drdiek** [comment]
@nmsutton I have tried a number of different ways to automate the formatting, but to no avail. I will continue to hand align as best as I can.

**Comment by drdiek** [comment]
@nmsutton I have tried reading through your dev doc notes, but I find them to be very opaque. I am unable to follow what you are trying to spell out. I need to increase the size of the headers by another 5 px, or so, to accommodate the longest names, but I am unsure, still, what all I need to do.

**Comment by nmsutton** [comment]
@drdiek yes, the header height dev doc notes are a work-in-progress and could use more filling out. I have added a bit more to them and I found that the matrix can be shifted as wanted by updating these values (note, the relevant values had +5 added to them):
main_nbyn.css
```
.frozen-bdiv {
  height:669px !important;
}
.ui-state-default .ui-jqgrid-hdiv {
  height:240px !important;
  /*height:57px;*/
}
.frozen-div {
  position: absolute !important; 
  height: 282px !important; 
  top: 0px !important; 
  left: 0px !important;
  z-index:5 !important;
}
```
nbyn_css_mods.php
```
$("#nGrid_Granule").css("height","260");
$('#nGrid_frozen').attr('style', 'width: 1px;height:400px;top:247px !important;position:relative !important;');
```
Please tell me if any issues come up applying the update

**Comment by nmsutton** [comment]
@drdiek please tell me, if I upload the latest nbyn_css_mods.php and main_nbyn.css on Github to the server will that show the completed version of this header height adjustment? Those files are up-to-date with your completed work on this?

**Comment by drdiek** [comment]
@nmsutton Because I am currently unable to get my local version of the portal working, I had to perform all of my testing on the actual phpdev site. Therefore, the site is fully up-to-date with regard to the files you mentioned. This Issue is fully solved and now closed, so you should be able to observe all of the corrected heights. If you notice any that are not fully corrected, please let me know, and I will reopen this Issue. I tested primarily on my Mac using Chrome and Safari.

**Comment by nmsutton** [comment]
@drdiek I have now made sure the files on phpdev and github are in sync with the updates you made. I also adjusted the left sidebar position a little. The text positions in the headers looks good, thanks very much for your work on this. Some are a little different than each other at least on my browser. Does the phpdev page for NOC look the same for you as it does for me in the screen shot attached? Also does the left sidebar look the same for you with proper alignment of the top and bottom of each section when scrolling with it? 

If the header text is a little off it is alright by me, seems like a low priority thing, but I wanted to see if it looks all aligned for you but different for me.
![noc_screenshot](https://user-images.githubusercontent.com/3514598/78934652-4d049980-7a79-11ea-9351-2696a9a2675c.png)

**Comment by drdiek** [comment]
@nmsutton All of the headers align well on my computer, and I just checked on my virtual Windows 10 machine using Edge, and they align there, too. I do not see the misalignment as depicted in your screenshot. In checking the alignment of the left sidebar, the left sidebar looks to be just a tick higher than the rest of the matrix, although it looks perfectly aligned in your screenshot.

**Comment by nmsutton** [comment]
@drdiek if this works fine in OSx and Windows, it is probably just a Linux thing. I updated the left sidebar size again, does it look correct in alignment for you now? If so, I propose that we don't need to change anything for this phase of the development before the article is submitted. We can reopen this issue just as a reminder for me to put code in to detect Linux and just for that but this is a low priority task that can be waited until a later time to work on compared to the final touches with the tool, etc.

**Comment by drdiek** [comment]
@nmsutton The From-To section is perfectly aligned. However, the sections below that one, which contain the neuron-type names, are all raised by 1 pixel from the rest of the side-scrolling matrix. This is true for both Chrome and Safari on my Mac and for Edge on my virtual PC.
