### ISSUE TITLE
GAA: [neurites] The hover over windows for the Somatic Distances matrix are producing incorrect values

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#510]
The distance along the axon of CA3 Pyramidal in SR has an average of 853.61, a minimum of 1168.35, and a maximum of 892.49, which doesn’t quite make sense.
Also affected are:
-CA3 PC SL_D
-CA3c PC SO, SP and SL for D
-CA3 Granule SLM_D
-DG Granule H_A
-DG Hilar Ectopic Granule SMo_D

**Comment by nmsutton** [comment]
@drdiek It seems I have fixed this. I ended up not converting the db columns into decimals because between MySQL and django used in csv2db creating empty cells with null values (which is required for every decimal cell) was more complicated than I wanted to spend time on now. I cast the db values to decimal in the query instead and it appears to have corrected it. Please review it and close the issue if completed.
