### ISSUE TITLE
GAA: [neurites] Remove 'Variance will be added later here" from Numbers of Potential Synapses N x N matrix hover-over box

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#512]

**Comment by nmsutton** [comment]
@drdiek I have completed this. Please review this work and close of completed.

**Comment by drdiek** [comment]
@nmsutton I notice not that for all three of the NxN matrices, the hover-over windows just repeat the values in the matrix. This seems very redundant. Is there an easy way just to remove them completely, or is it very involved?

**Comment by nmsutton** [comment]
@drdiek Well, this is a bit of a yes and no answer. What I have done is I updated the code so that hovering the mouse over the value no longer shows a tooltip hover over with the value. However, moving the mouse in a cell outside of the value still shows the hover over value but I think that may be a browser specific built in behavior. If that was wanted to be removed JQGrid parameters may need to be looked into and changed. Right now the columns values are loaded from json in the line "datastr: dataStr". Perhaps there is someway to enter JQGrid options to also remove the hoverover even when the mouse is not over the value but I don't know how to do that currently. Is it good enough to not have the hoverover come up when mousing over the value even if it shows in the white space of the cell?

**Comment by drdiek** [comment]
@nmsutton On my Mac, using Chrome, nothing is appearing when I hover over any of the NxN squares. On the other hand, when I use Safari, the hover-over windows are still appearing and echoing the number values. I consider this to be close enough.
