### ISSUE TITLE
GAA: [tool]: Connection probabilities tool does not list all possible postsynaptic types

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#517]
From Giorgio: "Another quick bug report on the tool: I noticed that when selecting CA3 pyramidal as presynaptic, CA3c pyramidal doesn’t appear in the postsynaptic dropdown; and then when selecting CA3c pyramidal as presynaptic, only CA3c pyramidal appears in the postsynaptic dropdown. Both behaviors are incorrect."

**Comment by nmsutton** [comment]
@drdiek it appears I have fixed this. On a separate note than fixing the missing values, in Nikhol's code there was a list of neuron types to exclude from the page's drop down options list if they were listed as targets even if in data/conndata.csv they are listed as targets for the source neuron. I removed that from excluding menu options because I don't understand if that was there for any reason other than a workaround. Please tell me if it was correct to remove it and if this issue now appears complete.
Exclusion list:
`let exclude = ["DG Axo-Axonic", "DG Basket" ,"DG Basket CCK+", "CA3 Axo-Axonic", "CA3 Horizontal Axo-Axonic" ,"CA3 Basket","CA2 Basket" ,"CA3 Basket CCK+","CA2 Basket+","CA2 Wide-Arbor Basket","CA1 Axo-Axonic","CA1 Horizontal Axo-Axonic","CA1 Basket","CA1 Basket CCK+","CA1 Horizontal Basket","SUB Axo-axonic","EC LII Axo-Axonic","MEC LII Basket","EC LII Basket-Multipolar","CA3 Interneuron Specific Oriens","CA3 Lucidum LAX","CA3 Lucidum-Radiatum","LEC LIII Multipolar Interneuron","MEC LIII Multipolar Principal","MEC LIII Multipolar Interneuron","EC LIII Pyramidal-Looking Interneuron"]`
