### ISSUE TITLE
KM: [Advanced search] Logically similar queries produce different results in the v2.0 advanced search

### ISSUE THREAD

**Issue by k1moradi** [Hippocampome-Org/php#520]
These two queries produce different results:

Neuron:(Morphology:(Axons:DG:1000 NOT Soma:DG:0000) NOT Name:Neurogliaform)
Neuron:(Morphology:(Axons:DG:1000 NOT Soma:DG:0000) NOT Name:(Neurogliaform))

**Comment by drdiek** [comment]
The correct result is:

[Screen Shot 2022-10-28 at 08.08.11.pdf](https://github.com/Hippocampome-Org/php/files/9888268/Screen.Shot.2022-10-28.at.08.08.11.pdf)


Neuron ID | Neuron Cell Type Nicknames
-- | --
1008 | MOPP
1013 | HIPP

Neuron ID	Neuron Cell Type Nicknames
1008	[MOPP](https://hippocampome.org/php/neuron_page.php?id=1008)
1013	[HIPP](https://hippocampome.org/php/neuron_page.php?id=1013)

Neuron ID | Neuron Cell Type Nicknames
-- | --
1008 | MOPP
1013 | HIPP

Neuron ID	Neuron Cell Type Nicknames
1008	[MOPP](https://hippocampome.org/php/neuron_page.php?id=1008)
1013	[HIPP](https://hippocampome.org/php/neuron_page.php?id=1013)

**Comment by drdiek** [comment]
The following query is giving the correct results:

Neuron:(Morphology:(Axons:DG:1000 NOT Soma:DG:0000) NOT Name:(Neurogliaform))

The following query is not giving the correct results because it is including "Neurogliaform" cells in the results, when it is not supposed to:

Neuron:(Morphology:(Axons:DG:1000 NOT Soma:DG:0000) NOT Name:Neurogliaform)
