### ISSUE TITLE
GAA: [neurites]: Missing values from Probability Evidence page

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#525]
From Giorgio: "I’ve started spot checking and the first couple clicks revealed an immediate bug: the absence of some evidence. As an example, following the probability from DG (i)0331 MOCAP to DG (i)3303 Total Molecular Layer and then auditing the hilus value pulls a blank for the postsynaptic data (convex hull 0, no segmentation, no figure)."

**Comment by drdiek** [comment]
@nmsutton I imagine this is somehow related to Issues #522 and #523. The file fragment_nbym.csv appears to be full of NULL values only.

**Comment by nmsutton** [comment]
@drdiek Thanks for the suggestiong. fragment_nbym.csv is actually no longer used, I just left it in csv2db for now. It was built on the space attachment_connectivity data, which was said to no longer be wanted. N by N pulls values from potential_synapses, number_of_contacts, and evidence articles from the morphology tables. I understand why it seems it might effect thing, but fragment_nbym.csv is depreciated; I just haven't removed the code from map.py yet. Removing that csv file is a low priority compared to other things, because it doesn't effect anything currently.

**Comment by nmsutton** [comment]
@drdiek an update is that it appears I have tracked down the source of the issue. Even though the issue is seen on the NbyN matrix, the update I did on Apr 15 of fragment_nbyk.csv (separate from fragment_nbym.csv) is causing the unwanted results. I will investigate further how to fix the issue.

**Comment by nmsutton** [comment]
@drdiek it appears this is fixed. I just sent an email out about it.

**Comment by nmsutton** [comment]
@drdiek if it helps, below is the query of the example mentioned in the email of an article figure with no convexhull values reported. I am assuming that it is fine that not all figures need that value.
```
SELECT convexhull FROM neurite_quantified WHERE unique_id=2000 AND neurite_quantified.neurite='CA3:SR:A' AND reference_id=800100;
```
