### ISSUE TITLE
NS: [neurites] Missing convex hull volume on Probability Evidence page

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#531]
From @nmsutton: "I want to describe also that in some cases there is not a convexhull volume reported for some article figures, but I assume that is acceptable. For example, pre: CA3 Pyramidal, post: CA3c Pyramidal, parcel: SR, article with Figure 5-7 (link) there is no convexhull for that in the database based on the source spreadsheet, but the other figures in that evidence do have convexhull values reported. This is not an error from the programming side, and I assume it is fine for this to be the case for some evidence entries."

For your example of CA1 Pyramidal to CA3c Pyramidal for CA3:SR, there should be two references, whereas all 4 citations are appearing under a single reference. The first listed axonal citation and he first listed dendritic citation are from Ishizuka et al., 1990, as is listed. The second axonal citation and second dendritic citation are from a book chapter Amaral et al., 2007. The reason the second axonal citation has no convex hull volume listed is that there are no axons depicted in the figure being cited, so something is fairly mixed up.

**Comment by nmsutton** [comment]
@drdiek I have fixed the issue with the correct number of articles/books appearing, thanks for reporting that. Something important to know about the evidence page for NbyN is that evidence is only shown for dendrites for the presynaptic neuron and only axons for the post synaptic neuron. That is due to those being the only relevant neurites for each neuron in the potential connection. Therefore, the evidence will only be for that and there should not be 4 total figure discriptions as you described but only 3, and the page now correctly show that with 1 for dendrite and 2 for axon ([link to page](http://www.hippocampome.org/phpdev/property_page_synpro_pvals.php?id_neuron_source=2000&id_neuron_target=2004&color=blue&page=1&nm_page=noc), click SR).

The issue remains that no convex hull value is reported for the Chapter 5 book entry. This appears to me to match the data in the neurite_quantified table. For example, that book entry is RefID 800100 and:
```SELECT convexhull FROM neurite_quantified WHERE unique_id=2000 AND neurite_quantified.neurite='CA3:SR:A' AND reference_id=800100;```
returns no convexhull volumes. However, 
```SELECT AVG(convexhull) FROM neurite_quantified WHERE unique_id=2000 AND neurite_quantified.neurite like 'CA3:SR:%' AND reference_id=800100;```
returns 2024673.372 as the value. The value may have only been reported for D but not A. Since only A is relevant here, as described above, you can please help explain if 1. the data truly is and should be missing, 2. it is acceptable to get a value from D event though that is not the neurite being used in the connection, or 3. the value from D should be added to A in the database table. Thanks in advance for the help.

**Comment by drdiek** [comment]
@nmsutton For Reference ID 800100, there are only convex hull volumes for dendrites in neurite_quantified.csv. There are absolutely no axonal convex hull volumes listed for that Reference ID, so I do not understand why the Evidence page is trying to display such.

**Comment by nmsutton** [comment]
@drdiek I agree with you. Please tell me, are you saying that if there are no convex hull values to report for the neurite of interest than the code should not display the "Convex hull volume in" line in the article/book reference for that neurite? Apologies if this seems like the answer is obvious but I want to make sure I am on the same page about this.

**Comment by drdiek** [comment]
@nmsutton What I am saying is that if there is no convex hull volume for the neurite of interest, then there should be no citation PERIOD. In the case of Reference ID 800100, the book citation should not be appearing at all, and I do not understand why it is appearing.

**Comment by nmsutton** [comment]
@drdiek thank for the feedback. The reason from what I understand why it is appearing is neurite_quantified lists the reference id for the book with the neuron-parcel combination: Neuron: CA1 Pyramidal (NeuronID=2000), Parcel='CA3:SR:A'. 
Example query: ```SELECT distinct reference_ID, convexhull FROM hippocsv2dbome.neurite_quantified WHERE unique_id = 2000 AND neurite = 'CA3:SR:A';```
Results: 
```reference_ID |  convexhull```
```'800098'    | '258743856.73'```
```'800098'    | ''```
```'800100'    | ''```
There is not yet a rule to omit an article reference based on a convex hull lack of value. I remember that in the article it states to calculate the number of contacts that "The expected number of points of contact in parcel x between a pair of neuron types is determined by the volume of interaction and the average intersection volume...To measure V_dx and V_ax , we extract the convex hull areas in parcel x from the isolated axonal and dendritic images for each reconstruction". To make sure I understand correctly, you are saying that if a convex hull value is not present for a reference in the number of contacts evidence page, I should prevent that reference from being shown in the evidence? Does that convex hull value rule affect any other evidence pages also?
Thanks,
Nate

**Comment by drdiek** [comment]
@nmsutton The Number of Potential Synapses depends only on the neurite lengths, so if one of them is not existent then there should be no entry on the Evidence page. The Number of Contacts depends on the neurite lengths and the convex hull volumes, so you have four chances of having a missing value and, therefore, have no Evidence page entry. The Connection Probabilities are calculated by dividing the NoPS by the NoC, so it is also dependent upon lengths and volumes being present.

**Comment by nmsutton** [comment]
@drdiek thanks for the additional details. I will get to work writing code to prevent displaying article/book references based on the criteria you described with the values needing to be present.

**Comment by nmsutton** [comment]
@drdiek a follow up question is - for the connection probability pages, you mentioned volumes, I don't think there are volume values associated with articles in the database. For that, should I just use length and convex hull as the article display dependent values?

**Comment by drdiek** [comment]
@nmsutton Volumes was short for convex hull volumes.

**Comment by nmsutton** [comment]
@drdiek I have added the requested code and it appear to have fixed this issue. Please review the pages and if this looks completed please close this.
