### ISSUE TITLE
KM: [synaptome]: Make a summary page for each potential connection

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#540]
Linking all the values on the matrix to synapse physiology page seems excessive and unnecessary as well. I suggest we make a page for each potential connection in which all the 5 parameters in 32 different conditions are shown in a unified table.
![Unified table](https://user-images.githubusercontent.com/4380011/84671322-3b19f980-aef5-11ea-9cb7-81214814051e.jpg)

**Comment by nmsutton** [comment]
@drdiek thanks very much for making these Github issues. One suggested update I would like is that the title of this issue be changed to "Make a summary page for each potential connection" where summary is said instead of evidence. This is because the page summarizes all relevant values and an evidence page would be something different. If this could be changed I would appreciate it, thanks.

**Comment by nmsutton** [comment]
@drdiek Thanks for updating the title. I have added the summary pages as links to any value on [the matrix](http://www.hippocampome.org/phpdev/synaptome_modeling.php). Please review this work and  close this if completed.
