### ISSUE TITLE
KM: [synaptic physiology]: “From” column of the table covers the horizontal scrollbar in the v1.0 Synaptic physiology matrix

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#550]
![image](https://user-images.githubusercontent.com/4380011/93604283-2a18d280-f993-11ea-8297-b8c759bbf9f0.png)

**Comment by drdiek** [comment]
This appears to be no longer an issue.

**Comment by nmsutton** [comment]
@drdiek I think this is browser/OS specific. On Linux Ubuntu 21.10 this issue still occurs in Chrome but not Firefox. A way to fix this is to include browser and OS detection code which changes the CSS. Another option is to just wait and see if the UI rendering matches in the future between browsers so that less browser specific code is needed.

**Comment by drdiek** [comment]
The display of the Synaptic Physiology matrix is quite variable depending on the browser/OS combination:

Firefox is problematic on MacOS 12.3.1, Windows 10 Pro 19043.1645, and Linux Ubuntu 18.10.
Firefox works on Linux Ubuntu 21.10.
Chrome is problematic on Linux Ubuntu 21.10.
Chrome works on MacOS 12.3.1 and Windows 10 Pro 19043.1645.
Edge works on MacOS 12.3.1 and Windows 10 Pro 19043.1645.
Safari works on MacOS 12.3.1.
