### ISSUE TITLE
GAA: [neurites] Add standard deviations to the results from the Connection Probabilities tool

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#555]

**Comment by nmsutton** [comment]
@drdiek to do this I should design to the tool use the length and volume values reported from the neurite_quantified table instead of ones in the /data/ files. Then it should take the mean and stdev of each value (based on lengths and volumes) resulting from users' changes to dendritic spine distance, inter-bouton distance, and radius of interaction parameters? Does that sound correct?

**Comment by drdiek** [comment]
@nmsutton That sounds correct.

**Comment by nmsutton** [comment]
@drdiek I have added code to include this functionality. I have attached ([rev_calc.zip](https://github.com/Hippocampome-Org/php/files/5293585/rev_calc.zip)) a page I wrote that helped me testing calculation values for an example pair (1002,1043), in case it might help you also. Please review the connection tool on phpdev and see if this is completed.

**Comment by drdiek** [comment]
@nmsutton This looks to be complete. The numbers of significant digits still need work, but I have opened a new ticket for those.
