### ISSUE TITLE
GAA: [neurites]: Correct how connection probabilities are summed across parcels for the NxN matrix and intermediate table

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#556]
@nmsutton Here is a modification to the instructions for how to propagate errors for the NxN matrices:

4) Sum values across all n_parcels parcels.
    c. Calculate the total mean connection probability and its standard deviation.
        i. CP_mean_total = 1 – ((1 - CP_mean_[parcel1]) * (1 - CP_mean_[parcel2]) * ...)
        ii. CP_stdev_total = CP_mean_total * sqrt((CP_stdev_[parcel1] / CP_mean_[parcel1])^2 + (CP_stdev_[parcel2] / 
            CP_mean_[parcel2])^2 + ...).

**Comment by nmsutton** [comment]
@drdiek I have added new code to include the formulas change. I have rebuilt the database and regenerated json for phpdev. The updated values are now present on the site. I noticed you changed the stdev_total equation as well as the mean_total equation. I assume this was for accommodation of the probabilities calculation using reciprocals, unless you say otherwise. I have included both new formulas for the new values. Please review the current values and see if this work is completed.

**Comment by drdiek** [comment]
@nmsutton Yes, I intentionally changed how stdev_total was calculated, too.
