### ISSUE TITLE
GAA: [neurites]: Match the number of significant digits between the Connection Probabilities tool results and the intermediate tables of the NxN matrices

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#557]

**Comment by nmsutton** [comment]
@drdiek please help me to understand the goal with this. Giorgio wrote in reference to the pair (2000,2000) "Let’s go with 3 significant digits in the numbers of contacts and 4 in the probabilities both in the parcels and in the totals. This requires adding a significant digit in the parcel probabilities obtained by clicking the matrix." However, I previously added code that I think you requested (unless I'm mistaken) that cuts off the decimal places (in the values by parcel page) for the parcel-specific values to match the total. For example, with total 0.01034, SO's .004421 becomes .00442 (to match the decimal places of the total). Should I stop using the code that makes that adjustment, because based his description it sounds like that is what he wants? Alternatively, is there interest in describing to him why that alteration is done to see if he wants it?

**Comment by nmsutton** [comment]
@drdiek in my meeting Giorgio asked what question there was about this so I talked to him a bit about this. He brought up an example where if two parcels have 0.055 values, yet the total is 0.11 than the parcel specific values would either be cropped to 0.05 or 0.06 but either way they would not add up to 0.11. He therefore supports just doing normal significant digits, and remove the code we added to have the number of parcel-specific decimal digits match the total. Please share, does that seem acceptable?

**Comment by drdiek** [comment]
@nmsutton I agree the parcel-specific values displayed do not necessarily have to match the the total value in terms of the number of significant digits, so the user can understand a situation such as 0.055 + 0.055 = 0.11.

**Comment by nmsutton** [comment]
@drdiek thanks, I have updated the code and reproduced the results with the property that all noc values have 3 significant digits and all connection probability values have 4 significant digits. The significant digits change is only made on final reported values, not intermediate calculations. For example, noc values remain their full digits for cp calcs but only for site display reporting they are changed. All values between main matrices, values by parcel page, and probability tool should now match. Please review this work and see if it has been completed.
