### ISSUE TITLE
GAA: [markers] The CA1 soma locations displayed in the main markers matrix are off

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#576]
I am not sure where the soma locations are being read in from, but the source file seems to have an error in it.

![Markers_matrix](https://user-images.githubusercontent.com/4380011/97762417-d1367100-1ade-11eb-9abb-9a258e1b8d36.jpg)

**Comment by drdiek** [comment]
@nmsutton Since this is affecting all of the sites, including the Main site, Giorgio recommended that I solicit some help from you in trying to solve this problem. The soma locations are all in the database, and I have spot checked the values showing up in the EvidencePropertyTypeRel table. The emboldened soma locations are displayed via getMarkers.php. In lines 195-206, the soma locations are read in. In lines 264-267, the emboldening of the soma locations takes place. Somewhere along the way, false soma locations are being displayed in the Markers matrix. For the life of me, I cannot tell where the false locations are coming from. I am limited in my ability to debug php code, so I have not been able to refine my tracing of the problem beyond the general lines of code I have already flagged.

**Comment by nmsutton** [comment]
@drdiek I have found the following related to this:
For one of the neurons listed (CA1 Axo-axonic, id 4036) the markers matrix is bolding the 2s because it is detecting the property of [545, somata, in, CA1:SO]. This is based on (for that neuron) my tracing line 267's $soma_position from neurite_pattern[$soma_position] retrieving from the $soma_location array "CA1:SO". 
In the query:
`SELECT distinct Property_id FROM EvidencePropertyTypeRel where Type_id = 4036 and Property_id > 500 and Property_id < 600;`
The results are 544 (CA1:SP) and 545 (CA1:SO) from the Property table.
In the results 545 (CA1:SO) appears in id #14194 and id #14148. When I change the Property_id from 545 to 544 in those two entries it causes the 3 to be bolded and the 2s to not be bolded in the CA1 Axo-axonic markers entry. This indicates to me that this not an issue with the source code, but instead an issue with the source data used on the markers page. 

That said, I don't know what "Neurite Patterns" means on the markers page. I also am unclear on what bold or not bold means. I assume an explanation is in the original article that the markers matrix was introduced in, but in my opinion, it could be nice to note an explanation of these things on the bottom of the markers page, or at least reference where the information can be found for people who visit the page and don't recall that info.

Do you agree that this appears to be a source data issue? I don't know which values for the source data would be correct so I refer to you about what the correct entries would be.

**Comment by nmsutton** [comment]
@drdiek I never heard back about this. Based on the recent milestone change, I'll assume that unless you tell me otherwise, other issues should be worked on before continuing with this one because the priority is low.

**Comment by drdiek** [comment]
@nmsutton Sorry I never got back to you on this. I recently changed the deadline for this to the end of March, because it is of lower priority at the moment.

**Comment by drdiek** [comment]
@knadellaCH Please remember that you need to distinguish between digit values of 0, 1, 2, 3 from digit positions 0th, 1st, 2nd, 3rd, 4th, 5th, 6th. You seem to still be emboldening all matching values rather than emboldening based on the positioning of the digits.
