### ISSUE TITLE
DWW: [phases]: For values in the Phases Evidence pages add errors and n values

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#597]
@nmsutton Currently the phases Evidence pages only list base values for parameters such as Theta. The database contains entries for errors, and I just now added entries for N values. If the errors and N values exist, I would like for the values displayed to look like this example for DG Granule cells:

Theta value(s): 115.67 ± 39.07 (3); Protocol: rats, adult, male and female, sharp pipette, urethane

If the error is not present or is equal to zero, then omit it.
If the N value is not present, then omit it. Even if the N value is equal to 1, it should still be displayed.

**Comment by nmsutton** [comment]
@drdiek please share, what column are the "N" entries in?

**Comment by nmsutton** [comment]
@drdiek I have now added on devur3 reporting of error values if they exist to evidence entries. Some thing that potentially appear missing are columns for run_stop_ratioError and run_stop_ratioErrorType. Was it intentional to not include those? 

I am not sure what "N" values you refer to. If it is meant to represent the number of values for the evidence entry, I'd like to describe that currently most evidence entries only have a single value, but in the case that there is more that one all values are displayed individually. For example, on the evidence page for neuron id 4098 ([link](http://www.hippocampome.org/devur3/neuron_page.php?id=4098)), the evidence entry with the value 320.75 also includes another value. The errors are individually matched to each value reported, and in this case of the two values, only 320.75 had an error value reported for it. Please tell me, if N represents the number of values, would that not be needed if all values are displayed individually?

**Comment by drdiek** [comment]
@nmsutton Apparently, I have not thought through this request thoroughly enough. Thank you for reporting the error values. I now consider this ticket to be completed, and I will write up a couple of new tickets concerning the determination of the various missing N values and their subsequent reporting on the portal, as it will take some work on my part to make the determinations. I will also create new tickets with respect to the determination and reporting of the error values for the run_stop_ratio. All of these new tickets I consider to be of lesser priority than the items I am currently addressing, which pertain directly to requests from the Reviewers.
