### ISSUE TITLE
LMdlP: [Neuron page]: The List of Articles on the Neuron pages only list morphology citations

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#607]
LMdlP: "When you click in the link to CA1 Superficial Pyramidal cell (elsewhere) a window pops up and shows a paper by Amaral (which is fine) but in the list of articles ours with Manuel is not listed. It should be included here. Same for CA1 Deep Pyramidal cell, but in this case there is no figure of a deep cell. Maybe our Fig.4A is useful (green cells are sup; red cells are deep): https://www.nature.com/articles/nn.4074"

@nmsutton Is there a way to list all of the papers that go into the content of a given Neuron page, not just the morphology-related ones?

**Comment by nmsutton** [comment]
@drdiek what I found out by looking into this is that the article evidence for phases were separate from the other site material because we intentionally separated them to avoid collision with the preexisting content in hippocampome. Therefore, I updated the neuron page to also include evidence articles retrieved from the separate phases db tables. It appears to be successfully retrieving the additional articles on devur3 now. For example, in the neuron page for "CA1 Superficial Pyramidal cell" (4098, [link](http://www.hippocampome.org/devur3/neuron_page.php?id=4098)) the (Valero M, 2015) article is now listed as referenced in the description of this task. Please review this work and see if it looks good. If it looks good I will add articles for the synapse probabilities pages as well, which are similarly in separate db tables. 

From what I have seen, the articles are not restricted to "morphology citations", but instead appear to have articles from all other pages than the phases and synpro pages. You could check that if you want as well. My reason for thinking this is that the evidence articles on the neuron page originally come from the query "SELECT DISTINCT Evidence_id FROM EvidencePropertyTypeRel WHERE Type_id = '$type_id'" and I don't see why that would be specific only to the morphology page.

**Comment by drdiek** [comment]
@nmsutton You are right. I now notice that there is a "Tags" line after each citations, which lists whether the citation has to do with morphology or markers. For some reason, none are tagged for electrophysiology, even though I see there is php code for it. Can you please add a Tag for "phase" citations?

**Comment by nmsutton** [comment]
@drdiek I have now added the phases tag. It can be seen on devur3.

I am confident that I can add the synpro articles to the neuron page and a tag for them. That would make 5/7 of the matrices with article evidence reported on the neuron page. In looking into the remaining two, connectivity (CON) and firing patterns (FP), I find their database records to be non-standard compared to those of the other matrices. I think you commented before about how a connectivity table did not look to be in good shape. I am concerned that trying to add CON and FP may be difficult. Given that we are trying to resubmit in a week as you mentioned, how important would you say adding CON and FP would be for that work? 

If it does turn out to look difficult, I propose we could mention (to Dr. de la Prida, not to a reviewer because a review never requested this) that due to those particular ones looking tricky we can look into adding them in the future but for the resubmission effort we at least have the majority added including the phases articles. Perhaps time could be better spent on things directly related to content from the phases work.

**Comment by drdiek** [comment]
@nmsutton This is great. I agree we can pass for now on the Connectivity and Firing Pattern tags.

**Comment by nmsutton** [comment]
@drdiek as a follow-up to this, I have now added the synapse probabilities articles and tag to the neuron page which I mentioned earlier I planned to do. No need to reopen this, this is just an update on what was previously discussed. If wanted you could review the addition but it appears to work from my tests.

**Comment by drdiek** [comment]
@nmsutton Thank you for following up on this. I agree that it appears to be working.
