### ISSUE TITLE
DWW: [phases] Add errors and N values to Evidence pages for in vivo firing rates

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#624]

**Comment by nmsutton** [comment]
@drdiek I am a bit confused here because it appears these are already reported. For example, in neuron id 1000 ([link](http://www.hippocampome.org/devur3/property_page_phases.php?id_neuron=1000&val_property=firingRate)) the first entries show "Firing rate value(s): 0.92 ± 0.78 (3);" and then "Firing rate value(s): 0.17 ± 0.26;". Is there something missing?

**Comment by drdiek** [comment]
@nmsutton I am not sure what I was looking at earlier, but everything does appear to be as it should be.
