### ISSUE TITLE
GAA: [phases] Add a new "Other" column to the main phases matrix

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#626]
@nmsutton After discussing all of the data that I have been mining, we decided to include more of the mined data in the matrix. Right now there is a column entitled "In Vivo Firing Rate (Hz)." This should now be changed to "Baseline Firing Rate (Hz)." A new "Other" column needs to be added after the "Epsilon" column that will be "Non-Baseline Firing Rate (Hz)," which will be a catch-all for all varieties of non-baseline firing rates. In the phases table is a column entitled "firingRateRank." The rank of all baseline firing rates is 1, and the ranks of all non-baseline firing rates are all greater than 1. How difficult will it be to add this new column? I could give it a try first, and only turn it over to you if I come up short, but I am especially concerned with how to incorporate the firingRateRank into the coding.

**Comment by nmsutton** [comment]
@drdiek in short, it is likely to be significantly complicated to do what you are asking (specifically for the firing rate ratio which is sorted by 2 different ranks) for multiple reasons and I suggest that you don't try to add this yourself. I can go into more detail in a larger post if wanted. I will need to add what you are describing. Please tell me, I thought we were trying to resubmit in a few days, why are we now expanding out the work in this way?

**Comment by drdiek** [comment]
@nmsutton Giorgio thought it would be worth adding this information to the matrix, if it could be done in a week or less. Do you think it would take more time than that? Would it help if I split out the non-baseline firing rates into their own column in the database? Or, do you think this is something that should be shelved for the expediency of the manuscript?

**Comment by nmsutton** [comment]
@drdiek thanks for the info. It is quite understandable naturally that this seems like a valuable thing to add so we are asked to add it. I think I can add it by Mar. 11th. Making a different column would be good because that would reduce the amount of source code that needs to be created to filter the firing rate column. Please do that, it would be helpful. I will then need to readjust the code to switch the double-filtered firing rate column into the other column. In brief, there were many pieces of code that were needed to have the double-filter, so shifting that to the other column will take some time but I am confident I can do it by that date, for one reason is that the double-filtered firing rate is working currently so shifting it conceptually seems accomplishable.

**Comment by drdiek** [comment]
@nmsutton I will do my best to set up the data as you request.

**Comment by nmsutton** [comment]
@drdiek thanks. Below is a query that may help. It returns firingRate values ordered first by metadataRank then second by firingRateRank. It is for cellID = 100 in this example. Also, a note is that it is acceptable for each cell to return multiple rows with firingRate values if they are all the same lowest metadataRank and firingRate rank (if there are ever multiples). I request such values are not averaged or have the median taken before my matrix code processes them because I have an adjusted median equation that is used, and should calculate the median in such a case for consistency. That said, I'm not sure that there would be such multiple values in this case.
```
SELECT 
 GROUP_CONCAT(DISTINCT id) AS id,
 GROUP_CONCAT(DISTINCT CAST(firingRate AS DECIMAL (10, 2 ))) AS val,
 GROUP_CONCAT(DISTINCT CAST(firingRateError AS DECIMAL (10, 2 ))) AS error_val,
 GROUP_CONCAT(DISTINCT firingRateN) AS error_val_n,
 GROUP_CONCAT(DISTINCT firingRateErrorType) AS error_type,
 GROUP_CONCAT(DISTINCT metadataRank) AS metadataRank,
 GROUP_CONCAT(DISTINCT firingRateRank) AS firingRateRank
FROM
 phases
WHERE
 cellID = 1000 AND firingRate != ''
GROUP BY metadatarank, firingRateRank
ORDER BY CAST(GROUP_CONCAT(DISTINCT CAST(metadataRank AS DECIMAL (10, 2 ))) AS DECIMAL (10, 2 )), 
	 CAST(GROUP_CONCAT(DISTINCT CAST(firingRateRank AS DECIMAL (10, 2 ))) AS DECIMAL (10, 2 ))
```

**Comment by drdiek** [comment]
@nmsutton I have finished updating the database for devur3. The original set of firing rate columns all have a firingRateRank of 1. The new non-baseline firing rate columns have firingRateRankNonBaseline values from 2-12.

**Comment by drdiek** [comment]
@nmsutton I have found instances where I have done the averaging in my spreadsheet. Are you saying that you would rather that I not do that and just leave it to you to take care of multiple values for a given neuron type for a particular metadatRank? Are you saying this for all categories of phases data, or just the firing rates?

**Comment by drdiek** [comment]
@nmsutton Do you need for me to separate out individual measurements from averages? If so, please let me know so I can do the work before you attempt to update the code.

**Comment by nmsutton** [comment]
@drdiek what I am refering to is that the values shown on the matrix for each column will always display a number that was a true value for the property. This is done by a median calculation that does not average an even number of middle values. For example, if theta values are [-55, 14, 22, 30] than 22 will be presented not 18. This I refer to as an "adjusted median" (AM). This calculation is due to as we have discussed previously that 18 really matches nothing experimentally found in terms of a theta phase value, and therefore avoiding the average makes scientific sense. This pertains to the new baseline fireRate column in the way that for each cell I would prefer (for the same reasons) if individual measurements were kept as values in the column so I can run the adjusted median calculation rather than having them already averaged. I refer to you to assess where in the data such an approach may be relevant. Thank you for you help with this and please tell me if any additional questions come up.

**Comment by drdiek** [comment]
@nmsutton OK, now I understand a bit better. It is making me realize that my averaging values in my spreadsheet and having just the average appear in the matrix is affecting what the users see. For instance, suppose your example of 22 is actually the average of values 19 and 25. I think, however, I will keep the averages in for now, as it will take a fair amount of work to separate out the individual values. This is something I can work on for a future ticket, but it is not worth potentially holding up the manuscript for.

**Comment by nmsutton** [comment]
@drdiek ok, that sounds fine. Thanks for checking in about it. From my understanding, my code automatically creates the adjusted median so it's likely we will be all set (with the matrix source code) for any update in the future that would change the data as you describe.

**Comment by drdiek** [comment]
@nmsutton That is my understanding of your code, too.

Just to confirm, the devur3 database is up to date and should work with the new code you are designing for the non-baseline firing rates.

**Comment by nmsutton** [comment]
@drdiek I think I may have the firingRateNonBaseline column working now. I did some testing and so far it appears working. Please check the values on the main matrix and evidence page to see if it appears working successfully.

During testing one thing I noticed is on the evidence pages and the main matrix is the values, e.g., for firingRateNonBaseline, are formatted to have 2 decimal places. However, in the source data some of the data is not that precise. I think this has already been discussed in the past because there was an interest in having the data have a uniform appearance, and variable decimal places would not appear that way. It is correct for the data to be presented in the way described, right? For example, the value 3 becomes 3.00.

**Comment by drdiek** [comment]
@nmsutton Everything looks good.

Yes, some of the values in my spreadsheet do not have any decimal places. After some checking, I found that sometimes this is the case in the original article, and sometimes it is a rounding on the part of Excel from 17.0 to 17, for instance. I think for consistency, we should leave all as it is with 2 decimal places. The user can always check the original citation if they are so inclined.

**Comment by drdiek** [comment]
@nmsutton I have updated the devur2 database. When you get the chance, could you please migrate over to devur2 all of the files that you have modified?

**Comment by nmsutton** [comment]
@drdiek I have now copied over my files. I forgot you mentioned you replaced the db so I also replaced the devur2 db with a copy of devur3's db today.
