### ISSUE TITLE
KM: [synaptic physiology]: Provide download links to parameter-linked .csv files

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#633]
@nmsutton "In short, @k1moradi  would like each of the 160 files in his Final_Synaptic_Data.rar archive to be dynamically set to be downloaded based on the select box conditions selection on the main matrix page of the site. That is, if it is not too complicated to add that web development, and alternatively, the "Final_Synaptic_Data.rar" file could simply be downloaded instead. I have set up a downloads folder on the server for his other files on the tools page at "/var/www/html/general/synapse_modeling/". Perhaps a folder could be created in that directory storing the 160 files if wanted. Possibly the $_REQUEST['param_1'] type of PHP variables contain the conditions selected but whoever works on this could check that."

**Comment by drdiek** [comment]
@k1moradi Perhaps you can add some clarification as to the naming of the files in question. Could you please provide a breakdown as to what each of the components of a file name means and how exactly they relate to the pull-down menu selections? Are multiple files supposed to be downloadable with each parameter combination? I notice that every file has the phrase "Th350," so does that even need to be mentioned in the file names? Also, I notice that there are 240 files, not 160, and sometimes you use the spelling FeMale instead of Female.

**Comment by nmsutton** [comment]
@k1moradi I notice now in the Final_Synaptic_Data there are x_center_x... files that were not in the earlier data from Oct '20. Those make up the difference of the 240 compared to 160 files I thought were in the collection. What are those? Are those definitely needed on the site? They have not been integrated into the site or database so far. If they are definitely necessary I will ask for help with integrating that new content if it needs to be propagated throughout the whole site. I may personally unfortunately have very limited time to participate in adding such content due to my commitments with the Cognome work.

**Comment by k1moradi** [comment]
For each of 32 conditions, five files should be provided for download: mean, sd, min, max, and cv files. We can zip the files in a package or provide five links for each. Whichever works. Is this clear now?

Th350 means slice thickness 350 micrometers that applies to all the inferences.

So x_center_x files do not directly correspond to the covariates conditions on the page. I used them for the analysis of covariates in Fig. 5 of the paper. We can safely delete them for now (or see my other proposal).

Another idea could be to rename the section on the page that right now is called "Source Experimental Data" to "Tools and Data" then under which we provide fixed download links for synaptome, synapse modeling tools, and a link to all the data in the "Final_Synaptic_Data.rar" file. This way all my results would be summarized in one page. (We can implement both these ideas.)

**Comment by drdiek** [comment]
@k1moradi What do Vh and Vss stand for?

**Comment by k1moradi** [comment]
Vh = holding potential of voltage clamp experiment
Vss = steady-state potential of current clamp experiment

**Comment by drdiek** [comment]
@k1moradi I would zip the five relevant files together to be downloaded in a single zip. Do you want to do this, or should I?

**Comment by k1moradi** [comment]
I can do it. Do you have any preference on how to name the files?

**Comment by drdiek** [comment]
@k1moradi The way the files are currently named is fine, just omit the initial XXX_. For example, you would end up with Vh=-60_P0_ISI50_T22_Th350_Female_P14_Mice_Cli=4_gluconatei=0.zip

**Comment by k1moradi** [comment]
@drdiek, you may download the files from my OneDrive now:

https://1drv.ms/u/s!Ato0Wsph7iDRq5sBRgQ9alsv8wqtHQ?e=wYJU6q

**Comment by drdiek** [comment]
@k1moradi I think I have the code working. Could you please take a look and provide any feedback you might have?

**Comment by k1moradi** [comment]
@drdiek Thanks for fixing this issue quickly! Everything looks good to me. The only thing that is strange is the on-load behavior. The first time the page loads the update button should have been invoked already to show default settings. Therefore, reinvoking it seems redundant. I think it should be possible to run your code on-load to have a download link on the first load as well. Alternately, we could hard code the link since the default settings are fixed and we already know which file should be there on the first load. Anyways, this is not a big deal even if this redundancy problem is not fixed. Thanks!

**Comment by drdiek** [comment]
@k1moradi I have changed the default behavior to link to the default settings file.

**Comment by k1moradi** [comment]
Everything looks good. I close the issue.
